<a href="https://colab.research.google.com/github/Prasad3617/IMAGE-MANIPULATIONS/blob/main/WEEK_10_PYTHON_PROGRAMMING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np   #importing necessary library

In [ ]:
a1=np.array([1,2,3])

a2=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [ ]:
print("\na1:",a1)


a1: [1 2 3]


In [ ]:
print("\na2:",a2)


a2: [[1 2 3]
 [4 5 6]
 [7 8 9]]


## datatype of the array

In [ ]:
print("\nThe datatype of the array a1 is:",a1.dtype)
print("\nThe datatype of the array a2 is:",a2.dtype)


The datatype of the array a1 is: int64

The datatype of the array a2 is: int64


## shape of the array

In [ ]:
print("\nThe shape of the array a1 is:",a1.shape)
print("\nThe shape of the array a2 is:",a2.shape)


The shape of the array a1 is: (3,)

The shape of the array a2 is: (3, 3)


## reshape an array

In [ ]:
a3=a2.reshape(9,1)
print("\nThe original array a2 is:\n",a2)
print("\nThe modified array a2 or a3 is:\n",a3)


The original array a2 is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

The modified array a2 or a3 is:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
# an array of string datatype

str_arr=np.array(["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])
print("\nThe array of string datatype is:\n",str_arr)


The array of string datatype is:
 ['Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday' 'Saturday']


## Array Creation Methods

### using "np.empty()"

In [ ]:
ar1=np.empty([3,3],int,'C')

In [ ]:
print(ar1)

[[ 4607825790175356063 -4611042647052049244  4603322190547985583]
 [-4611042647052049245  4617283349392834113 -4613744806828471525]
 [ 4603322190547985580 -4613744806828471527  4606153024599475607]]


### using "np.zeros()"

In [ ]:
ar2=np.zeros([3,3],float,'C')

In [ ]:
print(ar2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ar21=np.zeros([3,3],int,'C')

In [ ]:
print(ar21)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ar22=np.zeros(3,int)

In [ ]:
print(ar22)

[0 0 0]


### using "np.ones()"

In [ ]:
ar31=np.ones([3,3],int)

In [ ]:
print(ar31)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### using "np.asarrays"

In [ ]:
ar4=[1,2,3]   #a python list

In [ ]:
print(ar4)

[1, 2, 3]


In [ ]:
print(type(ar4))

<class 'list'>


In [ ]:
ar41=np.asarray(ar4,dtype=float)

In [ ]:
print(ar41,type(ar41))

[1. 2. 3.] <class 'numpy.ndarray'>


In [ ]:
print(type(ar41))

<class 'numpy.ndarray'>


In [ ]:
list1=range(5)

In [ ]:
print(list1)

range(0, 5)


In [ ]:
for i in list1:
    print(i)

0
1
2
3
4


In [ ]:
ar42=np.fromiter(list1,dtype=float)

In [ ]:
print(ar42)

[0. 1. 2. 3. 4.]


In [ ]:
print(type(ar42))

<class 'numpy.ndarray'>


### Creating arrays from Numerical Ranges

In [ ]:
x=np.arange(0,10,2,float)

In [ ]:
print(x)

[0. 2. 4. 6. 8.]


In [ ]:
y=np.arange(32,145,6,float)

In [ ]:
print(y)

[ 32.  38.  44.  50.  56.  62.  68.  74.  80.  86.  92.  98. 104. 110.
 116. 122. 128. 134. 140.]


### Creating arrays from Linspace

In [ ]:
z=np.linspace(10,20,15)

In [ ]:
print(z)

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ]


## Indexing and Slicing

In [ ]:
a=np.arange(20)

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
b=a[2:17:2]

In [ ]:
print(b)

[ 2  4  6  8 10 12 14 16]
